# Generated by Django 5.0.6 on 2024-07-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
